# ja
body_ja = """
2004生まれの高専生です

Rust / C / TypeScript を Arch Linux でいじったりしています

ウェアラブルコンピューティングやAR/MRを始めとするxR、HCI等に興味があります

これらの技術などを活用して、
[人間のやることを減らす](https://scrapbox.io/watasuke/%E5%A4%A2%E3%83%BB%E5%B0%86%E6%9D%A5%E5%83%8F%EF%BC%9F)
のが目標です
"""

# en
body_en = """
KOSEN (a.k.a. National College of Technology) Student

Creating something with Rust, C, TypeScript on Arch Linux

I'm interested in Wearable Computing, xR (especially AR/MR) and HCI

I'm eager to
 [reduce human tasks](https://scrapbox.io/watasuke/%E5%A4%A2%E3%83%BB%E5%B0%86%E6%9D%A5%E5%83%8F%EF%BC%9F)
 by using these technology
"""
